export const TEAM_FLAGS = {
    ALG: require("../assets/jogos/Algeria.png"),
    ARG: require("../assets/jogos/argentina.png"),
    AUS: require("../assets/jogos/australia.png"),
    AUT: require("../assets/jogos/austria.png"),
    BEL: require("../assets/jogos/belgium.png"),
    BIH: require("../assets/jogos/bosnia and herzegovina.png"),
    BRA: require("../assets/jogos/brazil.png"),
    CAN: require("../assets/jogos/canada.png"),
    CIV: require("../assets/jogos/ivory coast.png"),
    COD: require("../assets/jogos/democratic republic of congo.png"),
    COL: require("../assets/jogos/colombia.png"),
    CPV: require("../assets/jogos/cape verde.png"),
    CRO: require("../assets/jogos/croatia.png"),
    CUW: require("../assets/jogos/curacao.png"),
    CZE: require("../assets/jogos/czech republic.png"),
    DEN: require("../assets/jogos/denmark.png"),
    ECU: require("../assets/jogos/ecuador.png"),
    EGY: require("../assets/jogos/egypt.png"),
    ENG: require("../assets/jogos/england.png"),
    ESP: require("../assets/jogos/spain.png"),
    FRA: require("../assets/jogos/france.png"),
    GER: require("../assets/jogos/germany.png"),
    GHA: require("../assets/jogos/ghana.png"),
    GRE: require("../assets/jogos/greece.png"),
    HAI: require("../assets/jogos/haiti.png"),
    IRN: require("../assets/jogos/iran.png"),
    IRQ: require("../assets/jogos/iraq.png"),
    ITA: require("../assets/jogos/italy.png"),
    JOR: require("../assets/jogos/jordan.png"),
    JPN: require("../assets/jogos/japan.png"),
    KOR: require("../assets/jogos/south korea.png"),
    KSA: require("../assets/jogos/saudi arabia.png"),
    MAR: require("../assets/jogos/morocco.png"),
    MEX: require("../assets/jogos/mexico.png"),
    NED: require("../assets/jogos/netherlands.png"),
    NIG: require("../assets/jogos/nigeria.png"),
    NOR: require("../assets/jogos/norway.png"),
    NZL: require("../assets/jogos/new zealand.png"),
    PAN: require("../assets/jogos/panama.png"),
    PAR: require("../assets/jogos/paraguay.png"),
    POR: require("../assets/jogos/portugal.png"),
    QAT: require("../assets/jogos/qatar.png"),
    RSA: require("../assets/jogos/south africa.png"),
    RUS: require("../assets/jogos/russia.png"),
    SCO: require("../assets/jogos/scotland.png"),
    SEN: require("../assets/jogos/senegal.png"),
    SUI: require("../assets/jogos/switzerland.png"),
    SWE: require("../assets/jogos/sweden.png"),
    TUN: require("../assets/jogos/tunisia.png"),
    TUR: require("../assets/jogos/turkey.png"),
    UZB: require("../assets/jogos/uzbekistan.png"),
    URU: require("../assets/jogos/uruguay.png"),
    USA: require("../assets/jogos/united states.png"),
}